#!/usr/bin/env python3
"""
civ_workboard_gen.py — P1.2 of the self-running-AiCIV spine (sovereignty-spine #3).

GENERATES WORKBOARD §0 (MASTER TODO) as a VIEW over the durable ACG ops-board
(data/acg-ops-board/kanban.db), grouped by surface → owner_vp → project_id.

THE WHOLE POINT (the stale-§0 cure):
  Before this tool, WORKBOARD §0 was HAND-MAINTAINED. It went stale (the 06-17
  drift: a hand-edited §0 froze while the real state moved on). The unified-
  substrate design CLAIMED a `workflows/civ-workboard.js` generator "already
  exists" — it did NOT (walked 2026-06-21: file absent). This builds it.

  After this tool, §0 is a PURE FUNCTION of the .db. There is NO hand-edited §0
  to go stale: a stale .db row visibly drifts the generated board, and a regen
  fixes it. The .db (owned via the verb-only write-path, P1.1) is the single
  system-of-record; the board is its rendering.

THE GENERATED REGION (sentinel-bounded, the ONLY thing this tool writes):
  <!-- CIV-WORKBOARD:GENERATED §0 — DO NOT HAND-EDIT … BEGIN -->
  … grouped view rendered from kanban.db …
  <!-- CIV-WORKBOARD:GENERATED §0 — END -->

  Everything OUTSIDE the sentinels (the §0 header, the OWNER/LAST-UPDATED line,
  the open-work-register pointer, and all of §1..§9) is UNTOUCHED. This tool
  only owns the region between the sentinels. (RELATE-never-duplicate: §1..§9 are
  craft-VP writer-of-record surfaces; §0 is the cross-VP synthesis VIEW.)

HARD SAFETY (load-bearing — §0 is read by every fresh mind at wake-up step 4.5):
  - REVERSIBLE: the caller .bak's WORKBOARD.md once (timestamped sibling) before
    the FIRST generation retires the hand-§0. Rollback = restore the .bak.
  - PURE-FUNCTION: the generated region is derived ONLY from the .db read via
    PLAIN sqlite3 (no library import, no hidden state). Same .db → same region.
  - FAIL-LOUD: if the .db is missing, or §0 sentinels can't be placed
    deterministically (the §0 header isn't found, or a generated region exists
    but is malformed), this EXITS non-zero. A silent no-op on a broken board is
    the exact rot this tool exists to kill.
  - IDEMPOTENT: regenerating with no .db change re-writes a byte-identical
    region (modulo the LAST-GENERATED timestamp line). `check` proves drift.

Usage:
  python3 tools/sovereignty-spine/civ_workboard_gen.py render          # write the generated §0 into WORKBOARD.md
  python3 tools/sovereignty-spine/civ_workboard_gen.py render --dry-run # print the region to stdout, write nothing
  python3 tools/sovereignty-spine/civ_workboard_gen.py check           # exit 0 if WORKBOARD §0 == freshly-generated; exit 3 if drifted (stale)
  python3 tools/sovereignty-spine/civ_workboard_gen.py freshness       # report the board's last-generated stamp + the .db's last mutation
"""

import argparse
import json
import os
import re
import sqlite3
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path("/home/corey/projects/AI-CIV/ACG")
BOARD_DB = ROOT / "data/acg-ops-board/kanban.db"
WORKBOARD = ROOT / "WORKBOARD.md"

# Sentinels that bound the GENERATED region. Everything between (inclusive of the
# markers) is owned by this tool; everything outside is hand/VP-owned and untouched.
BEGIN = "<!-- CIV-WORKBOARD:GENERATED §0 — DO NOT HAND-EDIT (generated by civ_workboard_gen.py from kanban.db) — BEGIN -->"
END = "<!-- CIV-WORKBOARD:GENERATED §0 — END -->"

# The §0 header line we anchor the generated region UNDER (must exist; fail-loud if not).
SECTION0_HEADER_PREFIX = "## §0 MASTER TODO"
# The next section header after §0 — the generated region must end before it.
NEXT_SECTION_RE = re.compile(r"^## §[1-9]")

# Human-facing labels + ordering for the surfaces. A surface not in this map is
# rendered last under "OTHER" (fail-soft on a new surface, but it still appears).
SURFACE_DISPLAY = [
    ("MOON-PLAY", "🌙 MOON — PLAY/SHIP"),
    ("MOON-BUILD", "🌙 MOON — BUILD/DESIGN"),
    ("BLOG", "📰 BLOG"),
    ("WARREN", "📈 WARREN / PHARMA"),
    ("INFERENCE-PRODUCT", "💡 INFERENCE-PRODUCT"),
    ("CIV", "🏛️ CIV"),
    ("m3-combo", "🛰️ m3-combo / MNEME"),
    ("self-running-aiciv", "🧬 SELF-RUNNING AiCIV (the spine tracks its own build — meta builds meta)"),
]
SURFACE_ORDER = {s: i for i, (s, _) in enumerate(SURFACE_DISPLAY)}
SURFACE_LABEL = dict(SURFACE_DISPLAY)

# Statuses that count as OPEN (a board is the open-loop view). Everything else
# (done/cancelled) is summarized as a count, not enumerated — §0 is the WHAT'S-LEFT.
OPEN_STATUSES = {"ready", "blocked", "in_progress", "running", "claimed"}


def _connect():
    if not BOARD_DB.exists():
        sys.exit(f"FAIL-LOUD: board db not found: {BOARD_DB} — run the P1.1 cutover first")
    conn = sqlite3.connect(str(BOARD_DB))
    conn.row_factory = sqlite3.Row
    return conn


def _db_last_mutation(conn):
    """Newest mutation timestamp across tasks + task_events (the board's freshness)."""
    t = conn.execute("SELECT MAX(created_at) FROM tasks").fetchone()[0] or 0
    e = conn.execute("SELECT MAX(created_at) FROM task_events").fetchone()[0] or 0
    return max(int(t), int(e))


def _fetch_rows(conn):
    cols = {r["name"] for r in conn.execute("PRAGMA table_info(tasks)")}
    if not {"owner_vp", "surface", "project_id"} <= cols:
        sys.exit("FAIL-LOUD: ownership columns missing — run P1.1 (acg_ops_set_owner.py migrate) first")
    return conn.execute(
        "SELECT id, status, priority, owner_vp, surface, project_id, title "
        "FROM tasks ORDER BY surface, owner_vp, priority DESC, created_at"
    ).fetchall()


def _title_clean(title):
    """Strip the trailing '— **owner**' attribution (the owner is the group header now)."""
    t = re.sub(r"\s+", " ", (title or "")).strip()
    t = re.sub(r"\s*—\s*\*\*[^*]+\*\*\s*$", "", t)
    return t[:160]


def build_region(conn):
    """Build the GENERATED §0 region as a string (sentinel-bounded). Pure function of the .db."""
    rows = _fetch_rows(conn)
    total = len(rows)
    open_rows = [r for r in rows if r["status"] in OPEN_STATUSES]
    done_rows = [r for r in rows if r["status"] not in OPEN_STATUSES]
    last_mut = _db_last_mutation(conn)
    last_mut_iso = datetime.fromtimestamp(last_mut, tz=timezone.utc).strftime("%Y-%m-%d %H:%MZ") if last_mut else "unknown"
    gen_iso = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    # Group open rows: surface -> owner_vp -> [rows]
    by_surface = {}
    for r in open_rows:
        surf = r["surface"] or "CIV"
        by_surface.setdefault(surf, {}).setdefault(r["owner_vp"] or "(unowned)", []).append(r)

    surfaces_sorted = sorted(
        by_surface.keys(),
        key=lambda s: (SURFACE_ORDER.get(s, len(SURFACE_ORDER)), s),
    )

    out = []
    out.append(BEGIN)
    out.append("")
    out.append(f"> **GENERATED VIEW** — this region is a pure function of `data/acg-ops-board/kanban.db` "
               f"(grouped by surface → owner_vp). It is NOT hand-maintained; edit the .db via the "
               f"`set_owner_vp`/status verbs and regenerate. A stale .db row drifts this board on sight; "
               f"a regen fixes it. Generator: `tools/sovereignty-spine/civ_workboard_gen.py`.")
    out.append("")
    out.append(f"**LAST-GENERATED:** {gen_iso} · **DB-LAST-MUTATION:** {last_mut_iso} · "
               f"**OPEN:** {len(open_rows)} · **DONE/closed:** {len(done_rows)} · **TOTAL:** {total}")
    out.append("")

    for surf in surfaces_sorted:
        label = SURFACE_LABEL.get(surf, surf)
        owners = by_surface[surf]
        # owner ordering: by count desc, then alpha (stable, deterministic)
        owners_sorted = sorted(owners.keys(), key=lambda o: (-len(owners[o]), o))
        surf_count = sum(len(owners[o]) for o in owners_sorted)
        out.append(f"**{label}** ({surf_count} open):")
        for owner in owners_sorted:
            items = owners[owner]
            for r in items:
                pj = f" · `{r['project_id']}`" if r["project_id"] else ""
                blocked = " 🚫BLOCKED" if r["status"] == "blocked" else ""
                out.append(f"- [ ] **{owner}** · {_title_clean(r['title'])}{pj}{blocked} "
                           f"`[{r['id']}]`")
        out.append("")

    if not surfaces_sorted:
        out.append("_(no open rows — the board is clear)_")
        out.append("")

    out.append(f"> _Done/closed rows ({len(done_rows)}) are summarized here, not enumerated — §0 is the "
               f"open-loop view. The full history lives in the .db (`task_events`) + each section's DONE list._")
    out.append("")
    out.append(END)
    return "\n".join(out)


def _read_workboard():
    if not WORKBOARD.exists():
        sys.exit(f"FAIL-LOUD: WORKBOARD not found: {WORKBOARD}")
    return WORKBOARD.read_text(encoding="utf-8")


def _locate_section0(text):
    """Return (header_line_idx, body_start_idx, body_end_idx) for §0.

    body spans from the line AFTER the header up to (not incl) the next '## §N'.
    FAIL-LOUD if the §0 header is absent (we will not guess where §0 goes).
    """
    lines = text.splitlines()
    header_idx = None
    for i, ln in enumerate(lines):
        if ln.startswith(SECTION0_HEADER_PREFIX):
            header_idx = i
            break
    if header_idx is None:
        sys.exit(f"FAIL-LOUD: §0 header ('{SECTION0_HEADER_PREFIX}') not found in WORKBOARD — cannot anchor the generated region")
    body_start = header_idx + 1
    body_end = len(lines)
    for j in range(body_start, len(lines)):
        if NEXT_SECTION_RE.match(lines[j]):
            body_end = j
            break
    return lines, header_idx, body_start, body_end


def _split_region(body_lines):
    """Within §0 body lines, find the generated-region span if present.

    Returns (begin_idx, end_idx) indices INTO body_lines (inclusive of markers),
    or (None, None) if no generated region exists yet (first generation).
    FAIL-LOUD if a BEGIN exists without a matching END (malformed region).
    """
    begin_idx = end_idx = None
    for i, ln in enumerate(body_lines):
        if ln.strip() == BEGIN:
            begin_idx = i
        elif ln.strip() == END:
            end_idx = i
    if begin_idx is not None and end_idx is None:
        sys.exit("FAIL-LOUD: generated-region BEGIN marker present without END — region malformed, refusing to write")
    if end_idx is not None and begin_idx is None:
        sys.exit("FAIL-LOUD: generated-region END marker present without BEGIN — region malformed, refusing to write")
    if begin_idx is not None and end_idx is not None and end_idx < begin_idx:
        sys.exit("FAIL-LOUD: generated-region END precedes BEGIN — region malformed, refusing to write")
    return begin_idx, end_idx


# Lines OUTSIDE the generated region that must be PRESERVED at the top of §0 body
# (the OWNER/LAST-UPDATED line + the open-work-register pointer). On first
# generation we keep everything that precedes the first checkbox/subsection so we
# never lose the human-facing §0 preamble.
def _preserved_preamble(body_lines, begin_idx):
    """The §0-body lines BEFORE the generated region that we keep verbatim.

    If a region already exists, the preamble is everything before BEGIN.
    On first generation (no region yet), the preamble is the prose lines before
    the first checkbox or subsection header (the OWNER line + register pointer);
    the old hand-checkbox content is REPLACED by the generated region.
    """
    if begin_idx is not None:
        return body_lines[:begin_idx]
    # First generation: keep prose until the first checkbox '- [' or '**emoji ...:**' subsection.
    cb_re = re.compile(r"^\s*- \[")
    sub_re = re.compile(r"^\*\*.*:\*\*\s*$")
    keep = []
    for ln in body_lines:
        if cb_re.match(ln) or sub_re.match(ln.strip()):
            break
        keep.append(ln)
    return keep


def render(dry_run=False):
    conn = _connect()
    try:
        region = build_region(conn)
    finally:
        conn.close()

    if dry_run:
        print(region)
        return {"cmd": "render", "dry_run": True, "region_bytes": len(region)}

    text = _read_workboard()
    lines, header_idx, body_start, body_end = _locate_section0(text)
    body_lines = lines[body_start:body_end]
    begin_idx, end_idx = _split_region(body_lines)

    preamble = _preserved_preamble(body_lines, begin_idx)
    # Strip a trailing blank from the preamble so spacing is deterministic.
    while preamble and preamble[-1].strip() == "":
        preamble.pop()

    new_body = list(preamble)
    new_body.append("")  # one blank between preamble and the generated region
    new_body.extend(region.split("\n"))
    new_body.append("")  # trailing blank before the next section

    new_lines = lines[:body_start] + new_body + lines[body_end:]
    new_text = "\n".join(new_lines)
    if not new_text.endswith("\n"):
        new_text += "\n"
    WORKBOARD.write_text(new_text, encoding="utf-8")

    return {
        "cmd": "render",
        "dry_run": False,
        "workboard": str(WORKBOARD),
        "region_bytes": len(region),
        "had_existing_region": begin_idx is not None,
        "preamble_lines_kept": len(preamble),
    }


def _current_region(text):
    """Extract the current generated region from WORKBOARD text, or None."""
    if BEGIN not in text or END not in text:
        return None
    b = text.index(BEGIN)
    e = text.index(END) + len(END)
    return text[b:e]


def _strip_gen_timestamp(region):
    """Remove the LAST-GENERATED stamp line so check() compares content, not time."""
    if region is None:
        return None
    return re.sub(r"\*\*LAST-GENERATED:\*\*[^\n]*\n", "", region)


def check():
    """Exit 0 if WORKBOARD §0 == a freshly-generated region (modulo timestamp).
    Exit 3 (LOUD) if drifted — i.e. the board is stale relative to the .db."""
    conn = _connect()
    try:
        fresh = build_region(conn)
    finally:
        conn.close()
    text = _read_workboard()
    cur = _current_region(text)
    report = {"cmd": "check", "has_region": cur is not None}
    if cur is None:
        report["drifted"] = True
        report["reason"] = "no generated region present (board has not been generated yet)"
        print(json.dumps(report, indent=2))
        sys.exit(3)
    drifted = _strip_gen_timestamp(cur) != _strip_gen_timestamp(fresh)
    report["drifted"] = drifted
    if drifted:
        report["reason"] = "WORKBOARD §0 differs from a fresh render of the .db (stale board — regenerate)"
        print(json.dumps(report, indent=2))
        sys.exit(3)
    report["reason"] = "WORKBOARD §0 is a current pure-function rendering of the .db"
    print(json.dumps(report, indent=2))
    return report


def freshness(strict=False):
    """Report board last-generated vs .db last-mutation.

    `stale` is TRUE when the .db has mutated AFTER the board was last generated
    (a regen is owed — the wake-up consumer's time-based signal, complementary to
    `check`'s content-based signal). With --strict, exit 3 when stale so a cadence
    check can fail-loud without parsing JSON.
    """
    conn = _connect()
    try:
        last_mut = _db_last_mutation(conn)
    finally:
        conn.close()
    text = _read_workboard()
    cur = _current_region(text)
    m = re.search(r"\*\*LAST-GENERATED:\*\*\s*([0-9T:\- ]+Z)", cur or "")
    stamp = m.group(1).strip() if m else None
    # Compare on epoch: parse the board stamp back to a timestamp.
    board_epoch = 0
    if stamp:
        try:
            board_epoch = int(datetime.strptime(stamp, "%Y-%m-%d %H:%M:%SZ")
                              .replace(tzinfo=timezone.utc).timestamp())
        except ValueError:
            board_epoch = 0
    stale = (cur is None) or (last_mut > board_epoch)
    out = {
        "cmd": "freshness",
        "db_last_mutation": datetime.fromtimestamp(last_mut, tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ") if last_mut else None,
        "board_last_generated": stamp,
        "has_region": cur is not None,
        "stale": stale,
    }
    print(json.dumps(out, indent=2))
    if strict and stale:
        sys.exit(3)
    return out


def main():
    ap = argparse.ArgumentParser(description="ACG WORKBOARD §0 generator (P1.2 — VIEW over kanban.db)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    rp = sub.add_parser("render")
    rp.add_argument("--dry-run", action="store_true")
    sub.add_parser("check")
    fp = sub.add_parser("freshness")
    fp.add_argument("--strict", action="store_true",
                    help="exit 3 if the board is stale (db mutated after last generation)")
    args = ap.parse_args()

    if args.cmd == "render":
        print(json.dumps(render(dry_run=args.dry_run), indent=2))
    elif args.cmd == "check":
        check()
    elif args.cmd == "freshness":
        freshness(strict=getattr(args, "strict", False))


if __name__ == "__main__":
    main()
